### ISSUE TITLE
transrate to Japanese 注釈の日本語訳の修正

### ISSUE THREAD

**Issue by obimama** [dotnet/dotnet-api-docs.ja-jp#102]
指定した順序は、他のプロパティに指定された順序との相対値です。  たとえば、次の定義では、列Line1はLine2の前に表示され、Line2はCountryの前に表示されます。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: aef0a029-3141-1a1c-07a9-10fcf45b3be6
* Version Independent ID: 3fc73f51-e9c9-057c-d8bb-ed71cb78b52e
* Content: [ColumnAttribute.Order Property (System.ComponentModel.DataAnnotations.Schema)](https://docs.microsoft.com/ja-jp/dotnet/api/system.componentmodel.dataannotations.schema.columnattribute.order?view=netframework-4.8#feedback)
* Content Source: [xml/System.ComponentModel.DataAnnotations.Schema/ColumnAttribute.xml](https://github.com/dotnet/dotnet-api-docs.ja-jp/blob/live/xml/System.ComponentModel.DataAnnotations.Schema/ColumnAttribute.xml)
* Product: **dotnet-api**
* Technology: **system.componentmodel**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by srvbpigh** [comment]
Hello, @obimama
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@obimama

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/dotnet/api/system.componentmodel.dataannotations.schema.columnattribute.order?view=netframework-4.8

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team

**Comment by obimama** [comment]
Thank you for your consideration.
But the meaning is still different.

"Line1の前に表示" means "appears before Line1". (!)
Also, there is no Japanese saying "表示Countryします。". 
-> correct: "表示します。". 

"the column Line1 appears before Line2," -> "列Line1をLine2の前に表示し、" 
" and Line2 appears before Country." -> "Line2をCountryの前に表示します。" . 

I'm sorry if I commented on the old Doc.
(^_^)
