### ISSUE TITLE
Proposal abount explanation of HashSet in Japanese / HashSetの日本語訳の改善案

### ISSUE THREAD

**Issue by KobayashiKeisuke** [dotnet/dotnet-api-docs.ja-jp#104]
A part of Document of HashSet in Japanese is not suitable to understand for Japanese engineers.
I'd like you to confirm proposal below if possible.

Best Regards.

---
HashSet に関する説明が機械翻訳のためわかりづらい状態になっております。
一部だけですが改善案を下記に記載致しましたので、もしよろしければ採用していただけると有り難いです。

どうぞよろしくお願いいたします。

---

Original : 原文
```
The capacity of a HashSet<T> object is the number of elements that the object can hold. A HashSet<T> object's capacity automatically increases as elements are added to the object.

The HashSet<T> class is based on the model of mathematical sets and provides high-performance set operations similar to accessing the keys of the Dictionary<TKey,TValue> or Hashtable collections. In simple terms, the HashSet<T> class can be thought of as a Dictionary<TKey,TValue> collection without values.

A HashSet<T> collection is not sorted and cannot contain duplicate elements. If order or element duplication is more important than performance for your application, consider using the List<T> class together with the Sort method.

HashSet<T> provides many mathematical set operations, such as set addition (unions) and set subtraction. The following table lists the provided HashSet<T> operations and their mathematical equivalents.
```

Automatic Translation : 機械翻訳の内容
```
容量をHashSet<T>オブジェクトは、オブジェクトが保持できる要素の数。 AHashSet<T>オブジェクトに要素が追加されるオブジェクトの容量が自動的に増加します。

HashSet<T>クラスは、数学的なセットのモデルに基づいており、操作をセットのキーにアクセスするような高パフォーマンスを提供、Dictionary<TKey,TValue>またはHashtableコレクション。 簡単に言えば、HashSet<T>クラスとして考えることができます、Dictionary<TKey,TValue>なしの値のコレクション。

AHashSet<T>コレクションが並べ替えられていないと、重複する要素を含めることはできません。 順序または要素の重複が、アプリケーションのパフォーマンスがより重要な場合は、使用を検討して、List<T>クラスと組み合わせて、Sortメソッド。

HashSet<T> 多く数学的なセットの追加 (共用体) などの操作を設定し、減算の設定を提供します。 次の表に、指定された一覧HashSet<T>操作と、対応する数値。
```

Proposal : 改善案
```
HashSet<T>オブジェクトの容量は、保持しているオブジェクトの要素数と同じです。HashSet＜T>オブジェクトに要素が追加されるたびに容量は自動的に増加します。

HashSet<T>は数学の集合モデルに基づいたクラスで、Dictionary<TKey,TValue> やHashtableのkey にアクセスするのと同じような高パフォーマンスのset 操作を行えます。

HashSet<T>は 要素をソートされておらず、また重複要素を含めることができません。もし順序や重複した要素があなたのアプリケーションにとってパフォーマンスより重要であれば
List<T>クラスとSortメソッドの使用を検討してみてください。

HashSet<T>は集合の加算(和集合)や集合の減算など様々なの数学の集合に関する操作を提供しています。
下記の表ではHashSet<T>の操作と数学的な意味を掲載しています。
```

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 6b66ab1a-35aa-1bba-388c-30d698c1f50c
* Version Independent ID: d7dde1b9-fd16-dd30-6622-a15836579a9c
* Content: [HashSet&lt;T&gt; Class (System.Collections.Generic)](https://docs.microsoft.com/ja-jp/dotnet/api/system.collections.generic.hashset-1?view=netframework-4.8#feedback)
* Content Source: [xml/System.Collections.Generic/HashSet`1.xml](https://github.com/dotnet/dotnet-api-docs.ja-jp/blob/live/xml/System.Collections.Generic/HashSet`1.xml)
* Product: **dotnet-api**
* Technology: **system.collections**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by srvbpigh** [comment]
Hello, @KobayashiKeisuke
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @KobayashiKeisuke
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/dotnet/api/system.collections.generic.hashset-1?view=netframework-4.8#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
