### ISSUE TITLE
誤訳【戻り値】

### ISSUE THREAD

**Issue by gotomori** [dotnet/dotnet-api-docs.ja-jp#106]
-------------------現状-------------
戻り値
Boolean
true パラメーターが value または空の文字列 ("") の場合は null。それ以外の場合は false。
--------------提案-------------------
戻り値
Boolean
value パラメーターがnullまたは空の文字列 ("") の場合は true 。それ以外の場合は false。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 7f85d47a-5273-ffff-3ffa-fa4ca33a67ea
* Version Independent ID: 20b66376-055b-0113-4998-5139ec503ad0
* Content: [String.IsNullOrEmpty(String) Method (System)](https://docs.microsoft.com/ja-jp/dotnet/api/system.string.isnullorempty?view=netframework-4.8#feedback)
* Content Source: [xml/System/String.xml](https://github.com/dotnet/dotnet-api-docs.ja-jp/blob/live/xml/System/String.xml)
* Product: **dotnet-api**
* Technology: **system**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by srvbpigh** [comment]
Hello, @gotomori
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@gotomori

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/dotnet/api/system.string.isnullorempty?view=netframework-4.8#feedback

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
