### ISSUE TITLE
what do you mean '@no__t'?   '@no__t'は何を意味していますか？

### ISSUE THREAD

**Issue by anatawa12** [dotnet/dotnet-api-docs.ja-jp#113]
the list of '@no__t' is [here](https://github.com/dotnet/dotnet-api-docs.ja-jp/search?q=%27%40no__t%27&type=Code)

**Comment by srvbpigh** [comment]
Hello, @anatawa12
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by yamuun** [comment]
the same thing happens  ['@No__t-0'](https://github.com/dotnet/dotnet-api-docs.ja-jp/search?q=%27%40No__t-0%27&unscoped_q=%27%40No__t-0%27&type=Code)

**Comment by ticianaciminari** [comment]
@anatawa12:

Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://github.com/dotnet/dotnet-api-docs.ja-jp/search?q=%27%40no__t%27&type=Code. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team

**Comment by anatawa12** [comment]
@ticianaciminari Have this issue been fixed? In english page, this is fixed but in japansese page, this issue is not fixed

![Japanese page there is '@no___t'](https://user-images.githubusercontent.com/22656849/69214887-83fe0f80-0bab-11ea-901c-14cc5aba7674.jpeg)
![English page there is not '@no__t'](https://user-images.githubusercontent.com/22656849/69214889-8496a600-0bab-11ea-98cf-ae363f61a50a.jpeg)

**Comment by CeciAc** [comment]
Hi @anatawa12 
Thanks for your feedback.
We are actively working on this global fix. We estimate it'll be complete within this week.

Kind regards,
Microsoft DOCS International Team
