### ISSUE TITLE
取り消された状態になる条件が実際と逆

### ISSUE THREAD

**Issue by itn3000** [dotnet/dotnet-api-docs.ja-jp#13]
CancellationTokenが"取り消された状態"になる条件が、"すべてのソース トークンが取り消された状態であるとき"とありますが、
原文は"any of the source tokens are in the canceled state."なので、"いずれかのソーストークンが取り消された状態であるとき"というのが
正しい条件だと思います。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 230541ac-8c61-c03b-6fb2-6b3f31063710
* Version Independent ID: 3d30c19b-d1a7-5fa9-354e-f17b923635b8
* Content: [CancellationTokenSource.CreateLinkedTokenSource Method (System.Threading)](https://docs.microsoft.com/ja-jp/dotnet/api/system.threading.cancellationtokensource.createlinkedtokensource?view=netcore-2.2)
* Content Source: [xml/System.Threading/CancellationTokenSource.xml](https://github.com/dotnet/dotnet-api-docs.ja-jp/blob/live/xml/System.Threading/CancellationTokenSource.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
こんにちは、@itn3000

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@itn3000

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/dotnet/api/system.threading.cancellationtokensource.createlinkedtokensource?view=netcore-2.2

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
