### ISSUE TITLE
RegistryKey.GetValue Method

### ISSUE THREAD

**Issue by acup0fwhisky** [dotnet/dotnet-api-docs.ja-jp#18]
IOException
×：削除対象としてマークされ、指定された値を格納する RegistryKey。
○：指定された値を格納する RegistryKeyは、削除対象としてマークされています。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: fd565fa9-1fc2-cdf0-8b88-73b3c457ee8b
* Version Independent ID: 501bda5c-6dcf-c7d2-adc9-876f6984eb74
* Content: [RegistryKey.GetValue Method (Microsoft.Win32)](https://docs.microsoft.com/ja-jp/dotnet/api/microsoft.win32.registrykey.getvalue?view=netframework-4.7.2#Microsoft_Win32_RegistryKey_GetValue_System_String_)
* Content Source: [xml/Microsoft.Win32/RegistryKey.xml](https://github.com/dotnet/dotnet-api-docs.ja-jp/blob/live/xml/Microsoft.Win32/RegistryKey.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
こんにちは、@acup0fwhisky

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@acup0fwhisky

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/dotnet/api/microsoft.win32.registrykey.getvalue?view=netframework-4.7.2#Microsoft_Win32_RegistryKey_GetValue_System_String_

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
