### ISSUE TITLE
WhenAnyの翻訳が間違っています

### ISSUE THREAD

**Issue by prapra204** [dotnet/dotnet-api-docs.ja-jp#19]
指定されたすべてのタスクが完了してから～とありますが、これだとWhenAllの説明になり、正しくは「指定されたいずれかのタスクが完了してから～」だと思います。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1c50eacd-df85-b770-8975-b7bcc8cd3de2
* Version Independent ID: 6c1ba1c9-bbea-708d-1acb-992ffe03ee26
* Content: [Task.WhenAny Method (System.Threading.Tasks)](https://docs.microsoft.com/ja-jp/dotnet/api/system.threading.tasks.task.whenany?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.Threading.Tasks/Task.xml](https://github.com/dotnet/dotnet-api-docs.ja-jp/blob/live/xml/System.Threading.Tasks/Task.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
こんにちは、@prapra204

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@prapra204

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/dotnet/api/system.threading.tasks.task.whenany?view=netframework-4.7.2#feedback

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
