### ISSUE TITLE
It is incorrectly translated that "IList is added to Object".

### ISSUE THREAD

**Issue by P3PPP** [dotnet/dotnet-api-docs.ja-jp#20]
"パラメーター"の説明が間違っていて、追加する物と追加される物が逆になっています。
The explanation of "parameter" is incorrect, and the thing to be added and the one to be added are reversed.

誤り(現状): "Object に追加する IList。"
wrong(current): "Object に追加する IList。"

望ましい翻訳: "IList に追加する Object。"
desirable: "IList に追加する Object。"

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 32f51020-d6b6-e710-85b0-e71fa45792c9
* Version Independent ID: 2d3f7c96-c37b-00ee-aef7-beb020d327fd
* Content: [List&lt;T&gt;.IList.Add(Object) Method (System.Collections.Generic)](https://docs.microsoft.com/ja-jp/dotnet/api/system.collections.generic.list-1.system-collections-ilist-add?view=netframework-4.7.2#System_Collections_Generic_List_1_System_Collections_IList_Add_System_Object_)
* Content Source: [xml/System.Collections.Generic/List`1.xml](https://github.com/dotnet/dotnet-api-docs.ja-jp/blob/live/xml/System.Collections.Generic/List`1.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
こんにちは、@P3PPP

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@P3PPP  

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/dotnet/api/system.collections.generic.list-1.system-collections-ilist-add?view=netframework-4.7.2#System_Collections_Generic_List_1_System_Collections_IList_Add_System_Object_ 

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
