### ISSUE TITLE
Translation in Japanese

### ISSUE THREAD

**Issue by t-eimizu** [dotnet/dotnet-api-docs.ja-jp#7]
メソッドを「方法」と訳すのはありえないと思います。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: cfbcbb08-13cf-9183-0730-3b9d0bfabc31
* Version Independent ID: c8d89512-73e5-0628-7715-884c0176fcf9
* Content: [DataTable Class (System.Data)](https://docs.microsoft.com/ja-jp/dotnet/api/system.data.datatable?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.Data/DataTable.xml](https://github.com/dotnet/dotnet-api-docs.ja-jp/blob/live/xml/System.Data/DataTable.xml)
* Product: **dotnet-api**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by Fujiwo** [comment]
Although Japanese in https://docs.microsoft.com/ja-jp/dotnet/api/system.string?view=netframework-4.7.2 is just like machine translated and incorrect Japanese, it's not editable. I cannot edit it.

**Comment by mairaw** [comment]
It seems is a GitHub limitation when the file is too large. I think you'd have to clone the repo to submit a change in this case @Fujiwo.

**Comment by Fujiwo** [comment]
Thanks, I'll try it.

**Comment by CeciAc** [comment]
Hi @Fujiwo @mairaw  
We are working on this issue, is a template error so I assigned it to the owner team to fix it

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@t-eimizu

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/dotnet/api/system.data.datatable?view=netframework-4.7.2#feedback

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
