### ISSUE TITLE
「For more information, see...」を「詳細については、...を参照してください」

### ISSUE THREAD

**Issue by terasato** [dotnet/dotnet-api-docs.ja-jp#72]
The templated translation of "For more information, see... ." into "詳細については、次を参照してください。...ます。" is not grammatically correct in Japanese.

Regarding the same problem, I posted a PR to `dotnet/docs.ja-jp`. Please see [this PR](https://github.com/dotnet/docs.ja-jp/pull/592#issue-264358146).

Is it better that you handle this problem in your workflows? Or may I post a huge PR regarding this issue? Let me know which you want me to.

**Comment by mairaw** [comment]
@JasonCard FYI

If this translation is incorrect, it probably affects all content repos since this is used by all teams.

**Comment by CeciAc** [comment]
Hello, @terasato 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@mairaw @JasonCard please let me know if I can close this issue as "Duplicate" since it's already being worked by the CC team in the mentioned PR

**Comment by JasonCard** [comment]
@mairaw @CeciAc Thank you for flagging this. We are looking into fixing this issue globally in all Japanese repos. Since mentioned PR was for .NET Docs (dotnet/docs), let's keep this one opened until we can confirm fix in .NET API Docs (dotnet/dotnet-api-docs).

**Comment by JasonCard** [comment]
Hi @terasato 
Thank you again for your feedback.
We have run a script to fix all affected articles for Japanese that were machine translated. Changes should be reflected in live page within a day. 
Please let us know if you still find any issues.

Kind regards,
Microsoft DOCS International Team
cc @mairaw @CeciAc
